[package]
name = "pumpfinder"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = "1.0.1"
rand = "^0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.5"
num_cpus = "1.13"
bs58 = "0.4.0"
rand_core = "0.5.1"
